# Generated by Django 4.2.11 on 2024-05-20 21:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Causa',
                'verbose_name_plural': 'Causas',
                'db_table': 'Cause',
            },
        ),
        migrations.CreateModel(
            name='City_residence',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ciudad de recidencia',
                'verbose_name_plural': 'Ciudades de recidencia',
                'db_table': 'city_residence',
            },
        ),
        migrations.CreateModel(
            name='Country_residence',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'País de recidencia',
                'verbose_name_plural': 'Paises de recidencia',
                'db_table': 'country_residence',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='descripción')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'disability',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entry',
            },
        ),
        migrations.CreateModel(
            name='Ethnic_belonging',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('ethnic', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
                ('comunity', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Origen étnico',
                'verbose_name_plural': 'Origenes étnicos',
                'db_table': 'ethnic_belonging',
            },
        ),
        migrations.CreateModel(
            name='Nacionalities',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalities',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.occupation', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
                'db_table': 'occupation',
            },
        ),
        migrations.CreateModel(
            name='Opposition',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('manifest', models.CharField(max_length=50, unique=True, verbose_name='Manifestación')),
                ('date', models.DateTimeField(max_length=50, unique=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Oposición',
                'verbose_name_plural': 'Oposiciones',
                'db_table': 'opposition',
            },
        ),
        migrations.CreateModel(
            name='ShapeId',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Forma',
                'verbose_name_plural': 'Formas',
                'db_table': 'shape_id',
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Categoría')),
                ('date', models.DateTimeField(max_length=50, unique=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'triage',
                'verbose_name_plural': 'triages',
                'db_table': 'triage',
            },
        ),
        migrations.CreateModel(
            name='Wills_document',
            fields=[
                ('document', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Documento')),
                ('provider_code', models.CharField(max_length=50, unique=True, verbose_name='Codigo de prov')),
                ('date', models.DateTimeField(max_length=50, unique=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Documento de voluntad',
                'verbose_name_plural': 'Documentos de voluntades',
                'db_table': 'wills_document',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('full_name', models.CharField(max_length=250, null=True, verbose_name='Nombre Completo')),
                ('first_name', models.CharField(max_length=60, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo Nombre')),
                ('surname', models.CharField(max_length=60, verbose_name='Primer Apellido')),
                ('second_surname', models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo Apellido')),
                ('birthdate', models.DateTimeField(blank=True, verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(max_length=250, null=True, verbose_name='Sexo')),
                ('gender', models.CharField(max_length=250, null=True, verbose_name='Genero')),
                ('territorial_zone', models.CharField(max_length=250, null=True, verbose_name='Zona Territorial')),
                ('city_residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.city_residence', verbose_name='Ciudad de recidencia')),
                ('country_residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.country_residence', verbose_name='País de recidencia')),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.disability', verbose_name='Discapacidad')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.documenttype', verbose_name='Tipo de Documento')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.entity', verbose_name='Entidad')),
                ('ethnic_belonging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.ethnic_belonging', verbose_name='Origen étnico')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.nacionalities', verbose_name='nacionalidad')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.occupation', verbose_name='Ocupación')),
                ('opposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.opposition', verbose_name='Oposición')),
                ('wills_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.wills_document', verbose_name='Documento de ')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='IdModality',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('service_group', models.CharField(max_length=50, unique=True, verbose_name='Grupo de servicio')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.shapeid', verbose_name='Identidad de forma')),
            ],
            options={
                'verbose_name': 'Modalidad de identidad',
                'verbose_name_plural': 'Modalidades de identidades',
                'db_table': 'modalidad_ident',
            },
        ),
        migrations.CreateModel(
            name='Contact_service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('around', models.CharField(max_length=60, verbose_name='Primer Nombre')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.cause', verbose_name='Causa')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.diagnosis', verbose_name='Diagnóstico')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.entry', verbose_name='Entrada')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.idmodality', verbose_name='Modalidad')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.triage', verbose_name='triage')),
            ],
            options={
                'verbose_name': 'Servicio de contacto',
                'verbose_name_plural': 'Servicios de contactos',
                'db_table': 'contact_service',
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('document_type', 'identity_card'), name='UQ_DOCUMENT_TYPE_IDENTITY_CARD'),
        ),
    ]
