# Generated by Django 4.2.11 on 2024-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
