# Generated by Django 4.2.11 on 2024-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_alter_occupation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
