# Generated by Django 4.2.11 on 2024-05-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0003_alter_occupation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ips.occupation', verbose_name='Padre'),
        ),
    ]
