# Generated by Django 4.2.11 on 2024-05-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0004_alter_occupation_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opposition',
            name='code',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
