# Generated by Django 4.2.11 on 2024-05-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0005_alter_opposition_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wills_document',
            name='provider_code',
        ),
        migrations.AddField(
            model_name='wills_document',
            name='contact_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ips.contact_service', verbose_name='Codigo de prov'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opposition',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='wills_document',
            name='document',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='codigo'),
        ),
    ]
