# Generated by Django 4.2.11 on 2024-05-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0006_remove_wills_document_provider_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wills',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('document', models.CharField(max_length=3, unique=True, verbose_name='codigo')),
                ('date', models.DateTimeField(max_length=50, unique=True, verbose_name='Fecha')),
                ('contact_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ips.contact_service', verbose_name='Codigo de prov')),
            ],
            options={
                'verbose_name': 'Documento de voluntad',
                'verbose_name_plural': 'Documentos de voluntades',
                'db_table': 'wills',
            },
        ),
    ]
