# Generated by Django 4.2.11 on 2024-05-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0008_remove_patient_wills_document_patient_wills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wills_document',
        ),
    ]
