# Generated by Django 4.2.11 on 2024-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0009_delete_wills_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_residence',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
