# Generated by Django 4.2.11 on 2024-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0010_alter_city_residence_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='descripción'),
        ),
    ]
