# Generated by Django 4.2.11 on 2024-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0011_alter_entry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='descripción'),
        ),
    ]
