# Generated by Django 4.2.11 on 2024-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0012_alter_cause_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Descripción'),
        ),
    ]
